version: '3'

services:
  db:
    image: mysql
    restart: always
    environment:
      - MYSQL_HOST=localhost
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=blog_data
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - "./db:/var/lib/mysql"
 
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - DJANGO_SECRET=${DJANGO_SECRET}
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db